[windows]
win-server1 ansible_host=100.112.129.126 ansible_user=Administrador ansible_password='Cayoperico7'

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5986
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=https
