---
- name: Aplicar configuración común a todos los servidores
  hosts: lamp
  become: true
  roles:
    - common

- name: Configurar servidores web
  hosts: webservers
  become: true
  roles:
    - web

- name: Configurar servidores de base de datos
  hosts: dbservers
  become: true
  roles:
    - db
